### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by revolxof** [veld-chat/desktop-client#11]
# Needs to be added

## Message Actions

* [ ] Delete
* [ ] Edit
* [ ] Copy
* [ ] Quote/reply
* [ ] Message Reactions

## API
* [ ] Bot Libs
* [x] ID system 

## Misc
* [ ] Custom Emojis
* [ ] Channel Mentions
* [ ]  Image Embeds
* [ ]  Video Embeds
* [ ]  Actual Login States
* [ ]  DMs
* [ ] Stories

---

**Comment by CedarBlocks** [comment]
How could you forget about badges??? 😠
